name: PR Review Trigger

on:
  pull_request_review:
    types: [submitted]

jobs:
  review-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Review Info
        run: |
          echo "Pull Request was reviewed!"
          echo "Review State: ${{ github.event.review.state }}"
